#!/usr/bin/env python3
from pathlib import Path
import json,time,os
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[1]
results=[]
def check(name,condition,detail=None):
 results.append({'test':name,'pass':bool(condition),'detail':detail})
 if not condition:print('FAIL',name,detail)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),headless=False,args=['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-gpu-sandbox','--disable-gpu-rasterization'])
 page=b.new_page(viewport={'width':1600,'height':1100},device_scale_factor=1)
 errors=[];requests=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url))
 page.set_content((R/'index.html').read_text(),wait_until='load')
 page.wait_for_function('typeof Grid3D==="object"')
 check('324 visible data items',page.locator('#panel .item').count()==324)
 check('180 screenshot jack cells',page.evaluate('GRID_DATA.ports.length===180 && new Set(GRID_DATA.ports.map(x=>x.col+":"+x.row)).size===180'))
 check('144 unique control cells',page.evaluate('GRID_DATA.controls.length===144 && new Set(GRID_DATA.controls.map(x=>x.col+":"+x.row)).size===144'))
 check('Separate UI ids for jack/control counterparts',page.evaluate('new Set([...GRID_DATA.ports,...GRID_DATA.controls].map(x=>x.uid)).size===324'))
 check('18x10 grid completely filled',page.evaluate('GRID_DATA.ports.every(x=>x.col>=0&&x.col<18&&x.row>=0&&x.row<10)'))
 check('FOLD 2 left, FOLD 1 right',page.evaluate('GRID_DATA.ports.find(x=>x.id==="W2.IN").col===8&&GRID_DATA.ports.find(x=>x.id==="W1.IN").col===10'))
 check('MULT exactly one input and three outputs each',page.evaluate('["B1","B2"].every(b=>GRID_DATA.ports.filter(x=>x.block===b&&x.direction==="out").length===3)&&GRID_DATA.ports.filter(x=>x.block.startsWith("B")).length===8'))
 check('Six OFFSET columns below six ENV',page.evaluate('GRID_DATA.groups.filter(x=>x.field==="controls"&&x.block.startsWith("A")).every((x,i)=>x.col===12+i&&x.row===6)'))
 check('No silently added CV on A/B selectors',page.evaluate('["X1","X2"].every(b=>GRID_DATA.ports.filter(x=>x.block===b).map(x=>x.key).join()==="IN-A,IN-B,OUT")'))
 page.locator('[data-id="J:O1.SYNC"]').click()
 check('Selecting SYNC CV selects the jack, not the toggle','INPUT' in page.locator('#details').inner_text())
 page.locator('[data-id="C:O1.SYNC"] .state-choice[data-index="2"]').click()
 check('Three-position toggle selects requested state',page.evaluate('getGridSettings().values["O1.SYNC"]===2'))
 page.locator('[data-id="C:X1.SELECT"]').scroll_into_view_if_needed();page.locator('[data-id="C:X1.SELECT"]').click(position={'x':12,'y':18})
 check('New two-way switch stays two-state',page.evaluate('[0,1].includes(getGridSettings().values["X1.SELECT"])'))
 page.locator('[data-id="C:E1.RISE"]').focus();v=page.evaluate('GridRenderer.state(GRID_TEST.byId["E1.RISE"],getGridSettings())');page.keyboard.press('ArrowUp')
 check('Rotary AR keyboard adjustment',page.evaluate('GridRenderer.state(GRID_TEST.byId["E1.RISE"],getGridSettings())')>v)
 page.locator('#sh-slew').evaluate('(e)=>{e.value=1;e.dispatchEvent(new Event("input",{bubbles:true}));}')
 page.locator('#sh-input').evaluate('(e)=>{e.value=3.25;e.dispatchEvent(new Event("input",{bubbles:true}));}')
 page.locator('#sample').click()
 check('S&H captures selected input',page.evaluate('GRID_TEST.shHeld.H1===3.25'))
 page.locator('#sh-input').evaluate('(e)=>{e.value=-2;e.dispatchEvent(new Event("input",{bubbles:true}));}')
 check('S&H holds target while output glides independently',page.evaluate('GRID_TEST.shHeld.H1===3.25&&GRID_TEST.shVoices.H1.target===3.25&&GRID_TEST.shVoices.H1.output>0&&GRID_TEST.shVoices.H1.output<=3.25'))
 page.locator('#sh').select_option('H2');page.locator('#sample').click()
 check('Two S&H states independent',page.evaluate('GRID_TEST.shHeld.H1===3.25&&GRID_TEST.shHeld.H2===-2'))
 page.locator('#ab-a').evaluate('(e)=>{e.value=-2;e.dispatchEvent(new Event("input",{bubbles:true}));}');page.locator('#ab-b').evaluate('(e)=>{e.value=3;e.dispatchEvent(new Event("input",{bubbles:true}));}');page.locator('#ab-toggle').click();text=page.locator('#abvalue').inner_text();page.locator('#ab-toggle').click();text2=page.locator('#abvalue').inner_text()
 check('A/B changes one selected source, not a sum',text!=text2 and all('selected' in t for t in [text,text2]))
 page.locator('[data-id="J:M4A.SUM"]').click();page.locator('#volts [data-v="12"]').click()
 check('Mixer SUM clip indicator illuminates',page.locator('[data-led="M4A.SUM"][data-led-type="clip"]').get_attribute('opacity')=='1')
 check('OSC has no LEDs',page.locator('[data-led^="O"]').count()==0)
 check('Twelve AR stage lights',page.locator('[data-stage][data-env]').count()==12)
 before=page.evaluate('GridRenderer.pos(GRID_DATA.ports[0],getGridSettings())')
 page.locator('#labelJack').evaluate('(e)=>{e.value=1.8;e.dispatchEvent(new Event("input",{bubbles:true}));}')
 check('Text changes without moving hardware',page.evaluate('GridRenderer.pos(GRID_DATA.ports[0],getGridSettings())')==before)
 page.locator('#iconChoice').select_option('1')
 check('Existing icon variants still selectable',page.evaluate('getGridSettings().icons.OSC===1'))
 page.locator('#preset').select_option('square')
 check('Square grid gives 318x352 mm',page.evaluate('letD=GridRenderer.dims(getGridSettings());letD.w===318&&letD.h===352'))
 check('Pot shafts stay 6 mm in square preset',page.evaluate('GRID_DATA.controls.filter(x=>x.kind==="pot").every(x=>x.diameter_mm===6)'))
 page.locator('#preset').select_option('compact')
 check('Compact grid gives 318x298 mm',page.evaluate('letD=GridRenderer.dims(getGridSettings());letD.w===318&&letD.h===298'))
 page.locator('#bodies').check();check('Mechanical envelopes available',page.locator('.body-envelope').count()==324);page.locator('#bodies').uncheck()
 page.locator('#plugs').check();page.locator('#plugDia').fill('18');page.locator('#plugDia').dispatch_event('input');check('Oversized plugs warn', 'touch or overlap' in page.locator('#fit-warning').inner_text());page.locator('#plugs').uncheck()
 page.locator('[data-tab="research"]').click();page.locator('#part-search').fill('LF398')
 check('Component research filter works',page.locator('#parts tr').count()>=1 and 'LF398' in page.locator('#parts').inner_text())
 check('No outside network assets',not any(u.startswith(('http://','https://')) for u in requests))
 check('H1/H2 SLEW at only formerly empty cells',page.evaluate('["H1","H2"].every((b,i)=>GRID_TEST.byId[b+".SLEW"].col===7&&GRID_TEST.byId[b+".SLEW"].row===6+i)'))
 check('SLEW is a same-size 6 mm pot',page.evaluate('["H1","H2"].every(b=>GRID_TEST.byId[b+".SLEW"].diameter_mm===6)'))
 # Reload exact final artifact bytes for clean captures and a separate 3D test.
 page.set_content((R/'index.html').read_text(),wait_until='load');page.wait_for_function('typeof Grid3D==="object"')
 page.screenshot(path=str(R/'reports/desktop.png'))
 (R/'panels/panel.svg').write_text(page.evaluate('GridRenderer.render(GRID_DATA,getGridSettings()).svg'))
 # Capture actual text extents for the spacing review, without claiming all graphical clearances.
 ink=page.evaluate('''(()=>{let t=[...document.querySelectorAll('#panel text')].map(e=>{let b=e.getBBox();return {text:e.textContent,x:b.x,y:b.y,w:b.width,h:b.height};});let overlaps=[];for(let i=0;i<t.length;i++)for(let j=i+1;j<t.length;j++){let a=t[i],b=t[j],dx=Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x),dy=Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y);if(dx>.05&&dy>.05)overlaps.push([a.text,b.text,dx,dy]);}return {textCount:t.length,overlaps};})()''')
 (R/'reports/text-ink.json').write_text(json.dumps(ink,indent=2))
 check('Default text boxes do not overlap',len(ink['overlaps'])==0,ink['overlaps'][:10])
 page.locator('[data-tab="three"]').click();page.wait_for_function('window.GRID_3D_READY===true',timeout=20000);page.wait_for_timeout(1500)
 check('Real WebGL2 construction view',page.locator('#three canvas').count()==1 and page.evaluate('Grid3D.state().ready'))
 check('New SLEW interface board exists',page.evaluate('GRID_3D_LAYERS.some(x=>x.name.startsWith("UP"))'))
 check('New SLEW quad buffer allocation exists',page.evaluate('GRID_3D_ALLOCATION.some(x=>x.id.includes("SLEW dual-cell"))'))
 check('No fabricated circuit routing',all(x['kind'].startswith('package allocation') for x in page.evaluate('GRID_3D_ALLOCATION')))
 page.locator('#three canvas').screenshot(path=str(R/'studies/assembly.png'))
 frames0=page.evaluate('Grid3D.state().frames');data0=page.locator('#three canvas').evaluate('(c)=>c.toDataURL()');page.wait_for_timeout(750);data1=page.locator('#three canvas').evaluate('(c)=>c.toDataURL()')
 check('Stationary 3D frame stable',data0==data1)
 check('3D stops rendering when unchanged',page.evaluate('Grid3D.state().frames')==frames0)
 page.locator('#hide-panel').click();page.wait_for_timeout(300);page.locator('#three canvas').screenshot(path=str(R/'studies/boards.png'))
 page.locator('#explode').click();page.wait_for_timeout(400);page.locator('#three canvas').screenshot(path=str(R/'studies/exploded.png'))
 check('Exploded mode works',page.evaluate('Grid3D.state().exploded'))
 (R/'mechanical/core-allocations.json').write_text(json.dumps(page.evaluate('GRID_3D_ALLOCATION'),indent=2));(R/'mechanical/board-planes.json').write_text(json.dumps(page.evaluate('GRID_3D_LAYERS'),indent=2))
 page.locator('#explode').click();page.locator('#hide-panel').click();page.locator('[data-tab="split"]').click();page.wait_for_timeout(600);page.screenshot(path=str(R/'reports/split.png'))
 check('Flat + 3D both visible',page.locator('#flat-view').is_visible() and page.locator('#three-view').is_visible())
 page.locator('#px').evaluate('(e)=>{e.value=18;e.dispatchEvent(new Event("input",{bubbles:true}));}');page.wait_for_timeout(450)
 check('3D and flat use shared grid geometry',page.evaluate('Grid3D.state().lastKey==="18/14"') and '336 × 298' in page.locator('#size').inner_text())
 page.locator('#preset').select_option('compact');page.locator('[data-tab="flat"]').click();page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(300);page.screenshot(path=str(R/'reports/mobile.png'))
 check('No whole-page horizontal overflow on mobile',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
 check('No uncaught JavaScript errors',not errors,errors)
 version=b.version;b.close()
report={'browser':version,'navigation':'file:// blocked by environment policy; tested exact self-contained HTML bytes with set_content','webgl':'Headed Chromium under Xvfb, SwiftShader software WebGL2','passed':sum(x['pass'] for x in results),'total':len(results),'checks':results}
(R/'reports/browser-tests.json').write_text(json.dumps(report,indent=2));print(report['passed'],'/',report['total'],'passed')
if report['passed']!=report['total']:raise SystemExit(1)
