import collections,hashlib,json,subprocess,sys
from pathlib import Path
sys.path.insert(0,str(Path.cwd()))
from scripts.pcbgen.route_shards import copper_block_groups
from scripts.pcbgen.route_jack_grid import connectivity_signature,promotion_gate
root=Path('.circuit-cache/issue189-downloaded/jr-c7413-adoption/.circuit-cache');out=Path('circuit/routing/issue189/jr-c7413-endpoints');paths={s:root/('osc-jack-right-grid-shards-'+s) for s in ('start','merge','fresh')};d={s:json.loads((p/'dump.json').read_text()) for s,p in paths.items()};dr={s:json.loads((p/'drc.json').read_text()) for s,p in paths.items()};texts={s:(p/'osc-jack-right.kicad_pcb').read_text() for s,p in paths.items()};counts={s:collections.Counter(x for rows in copper_block_groups(t).values() for x in rows) for s,t in texts.items()}
r=json.loads((out/'adoption.json').read_text());pilot=json.loads((out/'pilot.json').read_text());assert r['adopted'] and r['candidate_board_sha256']==pilot['candidate_sha256'];assert r['copper_replay']['sha256']==pilot['replay_sha256'];assert promotion_gate(d['start'],d['merge'],dr['start'],dr['merge'])['adopted'];assert connectivity_signature(d['merge'])==connectivity_signature(d['fresh']);assert sum((counts['start']&counts['merge']).values())==51140;assert sum((counts['start']-counts['merge']).values())==5;assert sum((counts['merge']-counts['start']).values())==37
for k in ('pads','edges','keepouts','layers'):assert d['start'][k]==d['merge'][k]==d['fresh'][k]
for suffix in ('kicad_pro','kicad_dru'):assert len({(p/('osc-jack-right.'+suffix)).read_bytes() for p in paths.values()})==1
bot=subprocess.check_output(['git','show','origin/agent-fix/189-jr-c7413-adopt-worker:boards/osc-jack-right/osc-jack-right.kicad_pcb']);assert hashlib.sha256(bot).hexdigest()==r['candidate_board_sha256']==hashlib.sha256(texts['merge'].encode()).hexdigest();assert hashlib.sha256(Path('boards/osc-jack-right/osc-jack-right.kicad_pcb').read_bytes()).hexdigest()in (r['input_board_sha256'],r['candidate_board_sha256'])
proof=dict(run_id=37967123290,source_commit='01d88b8599a5b302e21f984fb4be520a64797152',bot_commit=subprocess.check_output(['git','rev-parse','origin/agent-fix/189-jr-c7413-adopt-worker']).decode().strip(),artifact_id=11633969149,artifact_sha256='afa07c7a1c2315162bcc62fa780a0e6e805f0082c4f59e5739ec000a097b8b5a',published_sha256=r['candidate_board_sha256'],replay_sha256=r['copper_replay']['sha256'],identical_uncut_objects=51140,added_objects=37,reviewed_removed_objects=5,native_edges=134,drc_errors=0,parity=0,warnings=520,new_warning_identities=[],split_pad_groups=[],fresh_agrees=True,physical_geometry_and_project_rules_unchanged=True,pilot_candidate_and_replay_match=True)
(out/'adoption-artifact.json').write_text(json.dumps(proof,indent=2)+'\n');print(proof)
