"""Rebase exact next jack cut scopes on native-accepted JL120/JR136 geometry."""
import json,hashlib,sys
from pathlib import Path
sys.path.insert(0,str(Path.cwd()))
from scripts.pcbgen.route_jack_grid import repair_selection,repair_bounds
for side,part,board,count,target,oldscreen in [('jl','2204','osc-jack-left',120,'C2248.2','jl121-ground-cut-screen'),('jr','8303','osc-jack-right',136,'R7609.2','jr137-ground-cut-screen')]:
 source=Path(f'circuit/routing/issue189/{oldscreen}/result.json');old=json.loads(source.read_text());t=next(x for x in old['transactions'] if x['pad']==target);p=Path(f'.circuit-cache/issue189-downloaded/{side}-u{part}-endpoints/{board}-grid-189-{side}{count+1}-u{part}-endpoints/dump.json');d=json.loads(p.read_text());boardsha=hashlib.sha256(Path(f'boards/{board}/{board}.kicad_pcb').read_bytes()).hexdigest();assert d['board_sha256']==boardsha
 ids=set(t['spec']['repair_source_uuids']);actual=[x for x in d['tracks'] if x['uuid'] in ids];assert sorted(actual,key=lambda x:x['uuid'])==sorted(t['selected_objects'],key=lambda x:x['uuid']);uid=t['spec']['repair_ground_pad_uuids'][0];assert next(g for g in d['islands']['AGND'] if uid in g)!=max(d['islands']['AGND'],key=len)
 stage={**t['spec'],'name':f'189-{side}{count}-{target.lower().replace(".","-")}-ground-cut','repair':True,'repair_layers':['F.Cu','B.Cu'],'clearance':.25,'signal_width':.2,'signal_via_diameter':.6,'grow':{'+12V':.05,'-12V':.05,'+5V':.05,'AGND':.05},'res':.025,'window_mm':6};repair_selection(d,stage);repair_bounds(d,stage,['AGND'],ids)
 plan={'board':board,'input_board_sha256':boardsha,'scope':f'Disposable {target} ground repair: {len(ids)} exact existing signal segments, {len(t["victim_nets"])} victim net; finite original frame; F/B-only restoration,300000expansion cap. Prior ground-only raster evidence is not a complete proposal. Cuts verified identical on newly accepted input; target still disconnected. Native original pad groups, retained endpoints, warning/DRC/parity/fresh gates mandatory; no canonical promotion.','stage':stage};dest=Path(f'circuit/routing/issue189/{side}{count}-{target.lower().replace(".","-")}-ground-cut');dest.mkdir(exist_ok=True);(dest/'plan.json').write_text(json.dumps(plan,indent=2)+'\n');Path(f'circuit/routing/issue189/{side}-local-plan.json').write_text(json.dumps(plan,indent=2)+'\n');(dest/'rebase.json').write_text(json.dumps({'status':'EXACT CUT GEOMETRY REBASED; NATIVE CUT/RESTORATION NOT RUN','source_screen_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'source_screen_board_sha256':old['board_sha256'],'accepted_board_sha256':boardsha,'input_dump_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'unchanged_selected_objects':actual,'target_pad':target,'victim_nets':t['victim_nets']},indent=2)+'\n');print(side,target,len(ids),'cuts, frame',stage['repair_bounds_mm'],'native NOT RUN')
