"""Pin the next disposable JL cut to native-accepted JL119; preserve recent copper."""
import hashlib,json,sys
from pathlib import Path
sys.path.insert(0,str(Path.cwd()))
from scripts.pcbgen.route_jack_grid import repair_selection,repair_bounds
source=Path('circuit/routing/issue189/jl121-ground-cut-screen/result.json');old=json.loads(source.read_text());target='U2205.9';t=next(x for x in old['transactions'] if x['pad']==target)
p=Path('.circuit-cache/issue189-downloaded/jl-u1518-adoption/.circuit-cache/osc-jack-left-grid-shards-fresh/dump.json');d=json.loads(p.read_text());sha=hashlib.sha256(Path('boards/osc-jack-left/osc-jack-left.kicad_pcb').read_bytes()).hexdigest();assert sha==d['board_sha256']=='554fa85a44d74c2ad2105e34f1bbc4de9b674e46dd7531ddc3e00c6d8e1c1291';assert d['open_edges']==119
ids=set(t['spec']['repair_source_uuids']);actual=[x for x in d['tracks'] if x['uuid'] in ids];assert sorted(actual,key=lambda x:x['uuid'])==sorted(t['selected_objects'],key=lambda x:x['uuid']);uid=t['spec']['repair_ground_pad_uuids'][0];assert next(g for g in d['islands']['AGND'] if uid in g)!=max(d['islands']['AGND'],key=len)
new_ids={r['uuid'] for r in json.loads(Path('circuit/routing/issue189/jl-u1518-joint/proposal.json').read_text())['copper']};assert not ids&new_ids
stage={**t['spec'],'name':'189-jl119-u2205-9-ground-cut','repair':True,'repair_layers':['F.Cu','B.Cu'],'clearance':.25,'signal_width':.2,'signal_via_diameter':.6,'grow':{'+12V':.05,'-12V':.05,'+5V':.05,'AGND':.05},'res':.025,'window_mm':6};repair_selection(d,stage);repair_bounds(d,stage,['AGND'],ids)
plan={'board':'osc-jack-left','input_board_sha256':sha,'scope':'Disposable U2205.9 ground repair: four identical original segments/two victim nets; no newly accepted JL119 copper cut. Finite original frame,F/B restoration,300000cap. Ground-only prefilter is not complete/native accepted. All original membership,warning,DRC/parity,fresh and retained-object gates mandatory.','stage':stage};dest=Path('circuit/routing/issue189/jl119-u2205-9-ground-cut');dest.mkdir(exist_ok=True)
for out in [dest/'plan.json',Path('circuit/routing/issue189/jl-local-plan.json')]:out.write_text(json.dumps(plan,indent=2)+'\n')
(dest/'rebase.json').write_text(json.dumps({'status':'EXACT SELECTED GEOMETRY VERIFIED ON ACCEPTED JL119; NATIVE TRIAL NOT RUN','source_screen_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'input_dump_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'accepted_board_sha256':sha,'unchanged_selected_objects':actual,'newly_accepted_copper_preserved':True,'victim_nets':t['victim_nets']},indent=2)+'\n');print('JL119 U2205.9:',len(ids),'cuts,',len(t['victim_nets']),'victims, bounds',stage['repair_bounds_mm'],'native NOT RUN')
