const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {Channel,tauFor}=require('../src/sh-slew-engine.js');let tests=[];
const run=(n,f)=>{f();tests.push({name:n,pass:true});};const near=(a,b,e=1e-10)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
run('No sample gives an explicitly invalid target',()=>{const a=new Channel();assert.equal(a.snapshot().target,null);a.advance(5);assert.equal(a.output,0);});
run('Minimum tau is 1.1 ms, not hard bypass',()=>near(tauFor(0),.0011));
run('Maximum tau is 251.1 ms',()=>near(tauFor(1),.2511));
run('Sample does not instantaneously step the output',()=>{const a=new Channel().setSlew(1).sample(5);assert.equal(a.output,0);assert.equal(a.target,5);});
run('One tau reaches 63.212 percent',()=>{const a=new Channel().setSlew(1).sample(5);a.advance(tauFor(1));near(a.output,5*(1-Math.exp(-1)));});
run('Negative input glides symmetrically',()=>{const a=new Channel().setSlew(.5).sample(-5);a.advance(tauFor(.5));near(a.output,-5*(1-Math.exp(-1)));});
run('Direction changes from the present output',()=>{const a=new Channel().setSlew(1).sample(5);a.advance(.1);let x=a.output;a.sample(-2);assert.equal(a.output,x);a.advance(.1);near(a.output,-2+(x+2)*Math.exp(-.1/tauFor(1)));});
run('Two channels remain independent',()=>{const a=new Channel(),b=new Channel();a.sample(4).advance(1);assert.equal(b.target,0);assert.equal(b.snapshot().sampled,false);});
run('Changing SLEW does not capture a new target',()=>{const a=new Channel().sample(2);a.setSlew(1);assert.equal(a.target,2);});
run('Changing SLEW preserves continuous output',()=>{const a=new Channel().setSlew(1).sample(2);a.advance(.1);let x=a.output;a.setSlew(0);near(a.output,x);});
run('Advancement is partition invariant',()=>{let a=new Channel().setSlew(.7).sample(5),b=new Channel().setSlew(.7).sample(5);a.advance(.12);for(let k=0;k<120;k++)b.advance(.001);near(a.output,b.output);});
run('Long paused frame remains stable',()=>{const a=new Channel().sample(3);a.advance(1e4);near(a.output,3);});
run('Nonfinite sample rejected',()=>assert.throws(()=>new Channel().sample(NaN)));
run('Negative dt rejected',()=>assert.throws(()=>new Channel().advance(-1)));
run('Nonfinite slew rejected',()=>assert.throws(()=>new Channel().setSlew(Infinity)));
run('Finite slew clamps at endpoints',()=>{near(tauFor(-1),tauFor(0));near(tauFor(2),tauFor(1));});
run('Output converges without overshoot',()=>{const a=new Channel().setSlew(.6).sample(4);for(let k=0;k<200;k++){let x=a.output;a.advance(.005);assert.ok(a.output>=x&&a.output<=4);}});
run('Five-volt step to ten millivolt error',()=>{const a=new Channel().setSlew(1).sample(5);a.advance(tauFor(1)*Math.log(500));near(5-a.output,.01);});
fs.writeFileSync(path.join(__dirname,'../reports/slew-tests.json'),JSON.stringify({scope:'Ideal first-order model only; not SPICE, LF398 droop, real protection, or hardware tests',passed:tests.length,total:tests.length,tests},null,2));console.log(tests.length+' SLEW model tests passed');
